### PR TITLE
RNMT-6057 ::: StatusBar plugin not working on Android apps built with MABS 9

### PR DESCRIPTION
**Pull request by andredestro**
### Platforms affected

- Android

### Motivation and Context

Fixes https://outsystemsrd.atlassian.net/browse/RNMT-6057

More context: https://github.com/apache/cordova-plugin-statusbar/pull/238

MABS 8 - Android 12
mabs8-android12

MABS 8 - Android 13
mabs8-android13

MABS 9 - Android 12
mabs9-android12

MABS 9 - Android 13
mabs9-android13

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by cmfsotelo — COMMENTED** [review]
Can you give more details as what this fix (for instance screenshots and scenario fixed), and also why we need this change (programattically speaking: like, was the old method discarded? were we doing something with deprecated APIs and we should now use the WindowInsetsControllerCompat?

Is there any other things we should/need to change on our code in the template? 🤔 

And also, don't forget that this alone won't fix our Shell, we need a commit there, after this one is merged and tagged.

And finally, could we contribute to the original repo, fixing the problem?

**Comment by usernuno** [comment]
The original PR from the upstream repo is this one: https://github.com/apache/cordova-plugin-statusbar/pull/238

This type of information should always be added to the PR description.

**Comment by andredestro** [comment]
> Can you give more details as what this fix (for instance screenshots and scenario fixed), and also why we need this change (programattically speaking: like, was the old method discarded? were we doing something with deprecated APIs and we should now use the WindowInsetsControllerCompat?
> 
> Is there any other things we should/need to change on our code in the template? 🤔
> 
> And also, don't forget that this alone won't fix our Shell, we need a commit there, after this one is merged and tagged.
> 
> And finally, could we contribute to the original repo, fixing the problem?

This piece of code is from the original repo. But was not released yet.
I will take some screenshot to update the PR.

**Review by cmfsotelo — APPROVED** [review]
@OutSystems/rd-mobile-core I was wondering if we should, in these cases, add the original PR link to the commit message, since the Code review might go undernoticed in the future when merging stuff

**Comment by tiagoappereira** [comment]
> @OutSystems/rd-mobile-core I was wondering if we should, in these cases, add the original PR link to the commit message, since the Code review might go undernoticed in the future when merging stuff

Can't we just cherry-pick the commits with the `-x` flag, which would point to the exact commit on the upstream?
Nevertheless, adding the PR link to the commit message seems reasonable and wouldn't harm anyone

**Comment by andredestro** [comment]
> > @OutSystems/rd-mobile-core I was wondering if we should, in these cases, add the original PR link to the commit message, since the Code review might go undernoticed in the future when merging stuff
> 
> Can't we just cherry-pick the commits with the `-x` flag, which would point to the exact commit on the upstream? Nevertheless, adding the PR link to the commit message seems reasonable and wouldn't harm anyone

But the commit doesn't exist in our fork yet. If I try a simple `git cherry-pick -x hash` it throws a `fatal: bad object` error.
Maybe, there is another way to do this, but I couldn't. Has @EiyuuZack any idea?

**Review by Chuckytuh — APPROVED** [review]

**Review by tiagoappereira — APPROVED** [review]
LGTM! Just a non-blocking comment. Looking at the referenced PR in the upstream repository, we see the following:

> It's a breaking change because it requires androidx.core, which is only available on cordova-android > 9. At the moment the plugin doesn't have any cordova-android version requirement, so requiring cordova-android > 9 is breaking.
A separate PR would be sent to set the engines if this PR gets accepted.

That "separate PR" is [this one](https://github.com/apache/cordova-plugin-statusbar/pull/241). Shouldn't we add this change too (although in reality, this makes no difference on MABS 9)?

**Review by EiyuuZack — APPROVED** [review]

**Review by usernuno — APPROVED** [review]

**Pull request merged**
